# Dockerfile for the backend

FROM python:3.8

# Mount current directory to /app in the container image
VOLUME ./:app/

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000:8000

ENTRYPOINT uvicorn backend:app --host 0.0.0.0 --port 8000 --reload
