# Dockerfile for the frontend

FROM python:3.8

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8501:8501

ENTRYPOINT streamlit run frontend.py
